#############################################################################
# Makefile for building: Switcher
# Generated by qmake (2.01a) (Qt 4.7.4) on: So 16. Sep 17:49:59 2012
# Project:  Switcher.pro
# Template: app
# Command: c:\qtsdk\symbian\sdks\symbiansr1qt474\bin\qmake.exe -spec c:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\mkspecs\symbian-sbsv2 -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o bld.inf Switcher.pro
#############################################################################

MAKEFILE          = Makefile
QMAKE             = c:\qtsdk\symbian\sdks\symbiansr1qt474\bin\qmake.exe
DEL_FILE          = del /q 2> NUL
DEL_DIR           = rmdir
CHK_DIR_EXISTS    = if not exist
MKDIR             = mkdir
MOVE              = move
DEBUG_PLATFORMS   = winscw gcce armv5 armv6
RELEASE_PLATFORMS = gcce armv5 armv6
MAKE              = make
SBS               = sbs

DEFINES	 = -DSYMBIAN -DUNICODE -DQT_KEYPAD_NAVIGATION -DQT_SOFTKEYS_ENABLED -DQT_USE_MATH_H_FLOATS -DQT_GUI_LIB -DQT_CORE_LIB
INCPATH	 =  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/include/QtCore"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/include/QtGui"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/include"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/mkspecs/common/symbian"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/stdapis"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/stdapis/sys"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/mw"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/mw"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/loc"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/mw/loc"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/loc/sc"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/mw/loc/sc"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/stdapis/stlportv5"  -I"C:/Users/AJ/Desktop/Code/QTProjects/switcher_v_1_0/Switcher/moc"  -I"C:/Users/AJ/Desktop/Code/QTProjects/switcher_v_1_0/Switcher/ui"  -I"C:/Users/AJ/Desktop/Code/QTProjects/switcher_v_1_0/Switcher" 
first: default

all: debug release

default: debug-winscw
qmake:
	$(QMAKE) "C:/Users/AJ/Desktop/Code/QTProjects/switcher_v_1_0/Switcher/Switcher.pro"  -spec c:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\mkspecs\symbian-sbsv2 -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

bld.inf: C:/Users/AJ/Desktop/Code/QTProjects/switcher_v_1_0/Switcher/Switcher.pro
	$(QMAKE) "C:/Users/AJ/Desktop/Code/QTProjects/switcher_v_1_0/Switcher/Switcher.pro"  -spec c:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\mkspecs\symbian-sbsv2 -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\Switcher.loc: 
	$(QMAKE) "C:/Users/AJ/Desktop/Code/QTProjects/switcher_v_1_0/Switcher/Switcher.pro"  -spec c:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\mkspecs\symbian-sbsv2 -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

debug: c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\Switcher.loc bld.inf
	$(SBS) -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1
clean-debug: bld.inf
	$(SBS) reallyclean --toolcheck=off -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1
freeze-debug: bld.inf
	$(SBS) freeze -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1
release: c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\Switcher.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1
clean-release: bld.inf
	$(SBS) reallyclean --toolcheck=off -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1
freeze-release: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1

debug-winscw: c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\Switcher.loc bld.inf
	$(SBS) -c winscw_udeb.mwccinc
clean-debug-winscw: bld.inf
	$(SBS) reallyclean -c winscw_udeb.mwccinc
freeze-debug-winscw: bld.inf
	$(SBS) freeze -c winscw_udeb.mwccinc
debug-gcce: c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\Switcher.loc bld.inf
	$(SBS) -c arm.v5.udeb.gcce4_4_1
clean-debug-gcce: bld.inf
	$(SBS) reallyclean -c arm.v5.udeb.gcce4_4_1
freeze-debug-gcce: bld.inf
	$(SBS) freeze -c arm.v5.udeb.gcce4_4_1
debug-armv5: c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\Switcher.loc bld.inf
	$(SBS) -c armv5_udeb
clean-debug-armv5: bld.inf
	$(SBS) reallyclean -c armv5_udeb
freeze-debug-armv5: bld.inf
	$(SBS) freeze -c armv5_udeb
debug-armv6: c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\Switcher.loc bld.inf
	$(SBS) -c armv6_udeb
clean-debug-armv6: bld.inf
	$(SBS) reallyclean -c armv6_udeb
freeze-debug-armv6: bld.inf
	$(SBS) freeze -c armv6_udeb
release-gcce: c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\Switcher.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1
clean-release-gcce: bld.inf
	$(SBS) reallyclean -c arm.v5.urel.gcce4_4_1
freeze-release-gcce: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1
release-armv5: c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\Switcher.loc bld.inf
	$(SBS) -c armv5_urel
clean-release-armv5: bld.inf
	$(SBS) reallyclean -c armv5_urel
freeze-release-armv5: bld.inf
	$(SBS) freeze -c armv5_urel
release-armv6: c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\Switcher.loc bld.inf
	$(SBS) -c armv6_urel
clean-release-armv6: bld.inf
	$(SBS) reallyclean -c armv6_urel
freeze-release-armv6: bld.inf
	$(SBS) freeze -c armv6_urel
debug-armv5-gcce4.4.1: c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\Switcher.loc bld.inf
	$(SBS) -c arm.v5.udeb.gcce4_4_1
clean-debug-armv5-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v5.udeb.gcce4_4_1
freeze-debug-armv5-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v5.udeb.gcce4_4_1
release-armv5-gcce4.4.1: c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\Switcher.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1
clean-release-armv5-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v5.urel.gcce4_4_1
freeze-release-armv5-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1
debug-armv6-gcce4.4.1: c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\Switcher.loc bld.inf
	$(SBS) -c arm.v6.udeb.gcce4_4_1
clean-debug-armv6-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v6.udeb.gcce4_4_1
freeze-debug-armv6-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v6.udeb.gcce4_4_1
release-armv6-gcce4.4.1: c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\Switcher.loc bld.inf
	$(SBS) -c arm.v6.urel.gcce4_4_1
clean-release-armv6-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v6.urel.gcce4_4_1
freeze-release-armv6-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v6.urel.gcce4_4_1

export: bld.inf
	$(SBS) export -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1 -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1

cleanexport: bld.inf
	$(SBS) cleanexport -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1 -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1

freeze: freeze-release

check: first

run:
	call C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/release/winscw/udeb/Switcher.exe $(QT_RUN_OPTIONS)

runonphone: sis
	runonphone $(QT_RUN_ON_PHONE_OPTIONS) --sis Switcher.sis Switcher.exe $(QT_RUN_OPTIONS)

Switcher_template.pkg: C:/Users/AJ/Desktop/Code/QTProjects/switcher_v_1_0/Switcher/Switcher.pro
	$(MAKE) -f $(MAKEFILE) qmake

Switcher_installer.pkg: C:/Users/AJ/Desktop/Code/QTProjects/switcher_v_1_0/Switcher/Switcher.pro
	$(MAKE) -f $(MAKEFILE) qmake

Switcher_stub.pkg: C:/Users/AJ/Desktop/Code/QTProjects/switcher_v_1_0/Switcher/Switcher.pro
	$(MAKE) -f $(MAKEFILE) qmake

sis: Switcher_template.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_sis:
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\createpackage.bat -g $(QT_SIS_OPTIONS) Switcher_template.pkg $(QT_SIS_TARGET) $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

unsigned_sis: Switcher_template.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_unsigned_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_unsigned_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_unsigned_sis:
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\createpackage.bat -g $(QT_SIS_OPTIONS) -o Switcher_template.pkg $(QT_SIS_TARGET)

Switcher.sis:
	$(MAKE) -f $(MAKEFILE) sis

installer_sis: Switcher_installer.pkg sis
	$(MAKE) -f $(MAKEFILE) ok_installer_sis

ok_installer_sis: Switcher_installer.pkg
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\createpackage.bat $(QT_SIS_OPTIONS) Switcher_installer.pkg - $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

unsigned_installer_sis: Switcher_installer.pkg unsigned_sis
	$(MAKE) -f $(MAKEFILE) ok_unsigned_installer_sis

ok_unsigned_installer_sis: Switcher_installer.pkg
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\createpackage.bat $(QT_SIS_OPTIONS) -o Switcher_installer.pkg

fail_sis_nocache:
	$(error Project has to be built or QT_SIS_TARGET environment variable has to be set before calling 'SIS' target)

stub_sis: Switcher_stub.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_stub_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_stub_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_stub_sis:
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\createpackage.bat -s $(QT_SIS_OPTIONS) Switcher_stub.pkg $(QT_SIS_TARGET) $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

deploy: sis
	call Switcher.sis

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc\moc_mainwindow.cpp moc\moc_tasksettings.cpp moc\moc_taskevent.cpp moc\moc_taskprioritythread.cpp moc\moc_taskpriorityprocess.cpp moc\moc_taskpriority.cpp moc\moc_rcqlistwidget.cpp moc\moc_taskaccessmanager.cpp moc\moc_systeminfo.cpp moc\moc_settings.cpp moc\moc_info.cpp moc\moc_log.cpp moc\moc_settingsstore.cpp moc\moc_test.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc\moc_mainwindow.cpp moc\moc_tasksettings.cpp moc\moc_taskevent.cpp moc\moc_taskprioritythread.cpp moc\moc_taskpriorityprocess.cpp moc\moc_taskpriority.cpp moc\moc_rcqlistwidget.cpp moc\moc_taskaccessmanager.cpp moc\moc_systeminfo.cpp moc\moc_settings.cpp moc\moc_info.cpp moc\moc_log.cpp moc\moc_settingsstore.cpp moc\moc_test.cpp
moc\moc_mainwindow.cpp: taskmanager.h \
		tasksettings.h \
		taskaccessmanager.h \
		taskpriority.h \
		taskpriorityprocess.h \
		taskprioritythread.h \
		taskevent.h \
		settingsstore.h \
		systeminfo.h \
		drivemanager.h \
		halmanager.h \
		log.h \
		settings.h \
		info.h \
		ckeycapturer.h \
		mainwindow.h
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\mainwindow.h -o c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\moc\moc_mainwindow.cpp

moc\moc_tasksettings.cpp: taskaccessmanager.h \
		taskmanager.h \
		taskpriority.h \
		taskpriorityprocess.h \
		taskprioritythread.h \
		taskevent.h \
		settingsstore.h \
		tasksettings.h
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\tasksettings.h -o c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\moc\moc_tasksettings.cpp

moc\moc_taskevent.cpp: taskaccessmanager.h \
		taskmanager.h \
		taskevent.h
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\taskevent.h -o c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\moc\moc_taskevent.cpp

moc\moc_taskprioritythread.cpp: taskmanager.h \
		taskprioritythread.h
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\taskprioritythread.h -o c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\moc\moc_taskprioritythread.cpp

moc\moc_taskpriorityprocess.cpp: taskmanager.h \
		taskpriorityprocess.h
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\taskpriorityprocess.h -o c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\moc\moc_taskpriorityprocess.cpp

moc\moc_taskpriority.cpp: taskpriorityprocess.h \
		taskmanager.h \
		taskprioritythread.h \
		taskpriority.h
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\taskpriority.h -o c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\moc\moc_taskpriority.cpp

moc\moc_rcqlistwidget.cpp: rcqlistwidget.h
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\rcqlistwidget.h -o c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\moc\moc_rcqlistwidget.cpp

moc\moc_taskaccessmanager.cpp: taskmanager.h \
		taskaccessmanager.h
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\taskaccessmanager.h -o c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\moc\moc_taskaccessmanager.cpp

moc\moc_systeminfo.cpp: taskaccessmanager.h \
		taskmanager.h \
		drivemanager.h \
		halmanager.h \
		settingsstore.h \
		log.h \
		systeminfo.h
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\systeminfo.h -o c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\moc\moc_systeminfo.cpp

moc\moc_settings.cpp: info.h \
		settingsstore.h \
		settings.h
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\settings.h -o c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\moc\moc_settings.cpp

moc\moc_info.cpp: info.h
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\info.h -o c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\moc\moc_info.cpp

moc\moc_log.cpp: settingsstore.h \
		log.h
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\log.h -o c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\moc\moc_log.cpp

moc\moc_settingsstore.cpp: settingsstore.h
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\settingsstore.h -o c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\moc\moc_settingsstore.cpp

moc\moc_test.cpp: test.h
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\test.h -o c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\moc\moc_test.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: ui\qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) ui\qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui\ui_mainwindow.h ui\ui_tasksettings.h ui\ui_taskevent.h ui\ui_taskprioritythread.h ui\ui_taskpriorityprocess.h ui\ui_taskpriority.h ui\ui_systeminfo.h ui\ui_settings.h ui\ui_info.h ui\ui_log.h
compiler_uic_clean:
	-$(DEL_FILE) ui\ui_mainwindow.h ui\ui_tasksettings.h ui\ui_taskevent.h ui\ui_taskprioritythread.h ui\ui_taskpriorityprocess.h ui\ui_taskpriority.h ui\ui_systeminfo.h ui\ui_settings.h ui\ui_info.h ui\ui_log.h
ui\ui_mainwindow.h: mainwindow.ui \
		rcqlistwidget.h
	c:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\uic.exe c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\mainwindow.ui -o c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\ui\ui_mainwindow.h

ui\ui_tasksettings.h: tasksettings.ui
	c:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\uic.exe c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\tasksettings.ui -o c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\ui\ui_tasksettings.h

ui\ui_taskevent.h: taskevent.ui
	c:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\uic.exe c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\taskevent.ui -o c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\ui\ui_taskevent.h

ui\ui_taskprioritythread.h: taskprioritythread.ui
	c:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\uic.exe c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\taskprioritythread.ui -o c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\ui\ui_taskprioritythread.h

ui\ui_taskpriorityprocess.h: taskpriorityprocess.ui
	c:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\uic.exe c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\taskpriorityprocess.ui -o c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\ui\ui_taskpriorityprocess.h

ui\ui_taskpriority.h: taskpriority.ui
	c:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\uic.exe c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\taskpriority.ui -o c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\ui\ui_taskpriority.h

ui\ui_systeminfo.h: systeminfo.ui
	c:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\uic.exe c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\systeminfo.ui -o c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\ui\ui_systeminfo.h

ui\ui_settings.h: settings.ui
	c:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\uic.exe c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\settings.ui -o c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\ui\ui_settings.h

ui\ui_info.h: info.ui
	c:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\uic.exe c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\info.ui -o c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\ui\ui_info.h

ui\ui_log.h: log.ui
	c:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\uic.exe c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\log.ui -o c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\ui\ui_log.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

dodistclean:
	-@ if EXIST "c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\Switcher_template.pkg" $(DEL_FILE)  "c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\Switcher_template.pkg"
	-@ if EXIST "c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\Switcher_stub.pkg" $(DEL_FILE)  "c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\Switcher_stub.pkg"
	-@ if EXIST "c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\Switcher_installer.pkg" $(DEL_FILE)  "c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\Switcher_installer.pkg"
	-@ if EXIST "c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\Makefile" $(DEL_FILE)  "c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\Makefile"
	-@ if EXIST "c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\Switcher_exe.mmp" $(DEL_FILE)  "c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\Switcher_exe.mmp"
	-@ if EXIST "c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\Switcher_reg.rss" $(DEL_FILE)  "c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\Switcher_reg.rss"
	-@ if EXIST "c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\Switcher.rss" $(DEL_FILE)  "c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\Switcher.rss"
	-@ if EXIST "c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\Switcher.loc" $(DEL_FILE)  "c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\Switcher.loc"
	-@ if EXIST "c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\bld.inf" $(DEL_FILE)  "c:\Users\AJ\Desktop\Code\QTProjects\switcher_v_1_0\Switcher\bld.inf"

distclean: clean dodistclean

clean: bld.inf
	-$(SBS) reallyclean --toolcheck=off -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1 -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1


